### ISSUE TITLE
Errors instead of println?

### ISSUE THREAD

**Issue by mrbenshef** [Blakeinstein/fuse-rust#3]
The usage of `println!` makes it difficult to use this crate in applications that want full control over stdout. Should they be errors instead?

Thanks for making this by the way, it's just what I was looking for!

**Comment by Blakeinstein** [comment]
I can definitely make those errors instead! I am learning rust, and did this as a project. Just give me some time, I have exam at the moment, and should be done with them by this week. I will convert string errors to actual Errors!

**Comment by Blakeinstein** [comment]
@mrbenshef Would you prefer Result<Vec<SearchResult>, String> or assertions?

I am unsure if `assert!()` takes control of stdout.

**Comment by mrbenshef** [comment]
Have you read the [error handling](https://doc.rust-lang.org/book/ch09-00-error-handling.html) section of the rust book? Also check out [this great talk from RustConf 2020](https://www.youtube.com/watch?v=rAF8mLI0naQ). 

Generally, you should use `Result` when the error is recoverable, and `assert!` when its not. I don't see any reason why the three instances shouldn't be recoverable in this case. For example [here](https://github.com/Blakeinstein/fuse-rust/blob/5e6b4ab2c538d156bc0dce9d39b2faca1683c4f4/src/lib.rs#L182), I wouldn't expect the empty string to be an invalid input because ultimately you are probably hooking this up to a searchbox where the empty string is a valid state (of the search box). Does that make sense?

**Comment by Blakeinstein** [comment]
I have decided to panic! when lookup fails, as at that point there is an error in the code, and removed the print statement when creating a pattern with an empty string, and just return None, so that searching will return none as well. I think returning None instead of the entire range, is better, since most search boxes, will have empty result list for empty search query.

I am pushing said changes, soon, as version 0.1.2 and for 0.2.0 I will convert the return value of create_pattern to a Result.

**Comment by Blakeinstein** [comment]
I am closing this issue, as it doesnt look like there are any more problems!
